### ISSUE TITLE
* wildcard expansion management

### ISSUE THREAD

**Issue by fucalerro** [fucalerro/42-minishell#3]
wildcard expansion must happen before the execution; regardless of the name of the files the wildcard expands them all.
So for example if we are in a dir with 2 files, on that is named `-n`, if we do `cat *` the `-n` will behave like an option of the cmd `cat`

hidden files (starting with `.`) are not included in the wildcard expansion

**Comment by Lu-ni** [comment]
If you name a program "ls" does it execute when you do just "*" ?

**Comment by fucalerro** [comment]
> If you name a file "ls" does it execute when you do just "*" ?

yes:
![image](https://github.com/fucalerro/42-minishell/assets/88712892/ef0b0e8d-caf9-4141-aa6c-f45a44700d23)

**Comment by fucalerro** [comment]
so during parsing we must simply expand `*` to all files in the current dir, sorted by alphabetical order (with special chars and numbers first) this is important

Also fun thing, you can name a file `*`. But it wont expand recursively (thanksfully) so we must not handle that case. It prints `command not found`.

**Comment by Lu-ni** [comment]
thats a bonus

**Comment by Lu-ni** [comment]
thats a bonus
